#!/bin/sh

device="scull"
mode="664"

case "$1" in
    start)
        echo "Loading scull module..."
        modprobe scull

        major=$(awk "\$2==\"scull\" {print \$1}" /proc/devices)

        rm -f /dev/${device}[0-3]
        mknod /dev/${device}0 c $major 0
        mknod /dev/${device}1 c $major 1
        mknod /dev/${device}2 c $major 2
        mknod /dev/${device}3 c $major 3
        ln -sf ${device}0 /dev/${device}
        chmod $mode /dev/${device}[0-3]
        ;;
    stop)
        echo "Unloading scull module..."
        rmmod scull || exit 1
        rm -f /dev/${device} /dev/${device}[0-3]
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0